### ISSUE TITLE
Issue with flashing Karadio on TTGO-TM-ESP32

### ISSUE THREAD

**Issue by kang2k10** [karawin/KaRadio32_4#16]
![Снимок экрана 2024-06-03 163826](https://github.com/karawin/KaRadio32_4/assets/55108857/30826332-cb93-4c84-9e68-fee37c6f2512)
```
test offset :  65536 0x10000
case ok
test offset :  1900544 0x1d0000
case ok
test offset :  32768 0x8000
case ok
test offset :  4096 0x1000
case ok
test offset :  3809280 0x3a2000
case ok
Traceback (most recent call last):
  File "download_process.py", line 447, in OnButton_StartButton
  File "download_process.py", line 425, in start_func
  File "download_process.py", line 662, in flash_config
IndexError: index out of range
```
If i uncheck ttgotm.bin, flashing is done

**Comment by Adhelor** [comment]
1. No empty lines are allowed - so remove them before building your own *.bin file
2. There is mandatory "header" in the first line of csv:
                key,type,encoding,value
    and "section headers"
                label_space,namespace,,         //second line
                gpio_space,namespace,,          //before K_SPI definition
                option_space,namespace,,        //before O_XXX - option definisions
                custom_ir_space,namespace,,     //before K_XXX - IR keys definition
